[features]
seeds = false
skip-lint = false
[programs.localnet]
block_book = "5EtTrvMn7TX7UAh9jwskq6Rmy9nQyvjFfvy2g7Nn1vgs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/gloves/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
hello-script = "echo 'Hello World'"